### ISSUE TITLE
Undeclared signal "Routing-Update" emitted (@signal missing from NED file?).

### ISSUE THREAD

**Issue by gaixas1** [kvetak/RINA#19]

**Comment by kvetak** [comment]
Hi, Sergio!

I have fixed missing declaration of signal and this particular error should be fixed in the current master https://github.com/kvetak/RINA/commit/e4679e79396f9a144ac7f78252915bf6fb31aadb. Since I am not an author of any Routing example, I would like to ask you to check, whether scenarios behave OK.

So far I have found bug in /examples/Routing/DDC in your module FlowListener which is casting error related to the object contained in the signal.

I will coordinate with @kjerabek checking of DAF configuration in order to have example fully compatible with the new RINASim.

**Comment by kvetak** [comment]
Kamile @kjerabek  ! I kindly ask you to check (and if possible repair) DAF components configuration in following scenarios:

/examples/Routing/BigDC
/examples/Routing/FatTreeTopology
/examples/Routing/RCoreNet
/examples/Routing/UnreliableLinks
/examples/Routing/LatEx

Use some previous version of RINASim as the baseline where these examples seem to work.

**Comment by gaixas1** [comment]
Some of these examples should be corrected (or deleted) as the version in
sim is old now when pulling my branch into master (all data injection and
similar has been changed there and examples modified)

2016-11-17 13:08 GMT+01:00 Vladimir Vesely <notifications@github.com>:

**Comment by gaixas1** [comment]
I will check it, but better after mergin my changes into master (some
examples already corrected there) and most "extra" code modified.

2016-11-17 13:04 GMT+01:00 Vladimir Vesely <notifications@github.com>:

**Comment by kvetak** [comment]
Okay, I will merge it right now, after I successfully compile it and test few Demos at my computer.

**Comment by kvetak** [comment]
@gaixas1 You can continue in master branch, I have successfully merged your contribution into master. As soon as you will tell me that everything is okay from your perspective, we will create a new fingerprints and tag that RINASim version for your convenience of future referencing.

**Comment by gaixas1** [comment]
ok

2016-11-17 14:18 GMT+01:00 Vladimir Vesely <notifications@github.com>:

**Comment by kjerabek** [comment]
Hi,
I checked scenarios you mentioned.

/examples/Routing/LatEx
  - Repaired and working.

/examples/Routing/RCoreNet
  - The problem was in ini file with naming, ipcProcess[... instead of ipcProcess0[...
  - Repaired and working.

/examples/Routing/BigDC
  - There should be a similar problem like in the case above. I was not 100% sure about that, so I did not repaired it. Please check it.

/examples/Routing/FatTreeTopology
  - I repaired daf configuration, but it looks like there is another problem.
/examples/Routing/UnreliableLinks
  - The same as above.

**Comment by kvetak** [comment]
I consider this issue as resolved, thus, I am closing it. Generally, in NED files there are still some leftovers of intentionally commented signals. The reason is that with migration towards OMNeT++ 5.0 where signal checking is mandatory, we wanted to double-check existing signals (and get rid off unused ones). 

So anytime in the future when you receive Undeclared signal error, inspect parent NED file first. Related link to this issue https://omnetpp.org/9-articles/software/3713-omnet-441-released .
